AWSTemplateFormatVersion: '2010-09-09'
Description: Fase 2 - Certificado SSL, CloudFront OAC e DNS Record para willdiniz.com.br

Parameters:
  DomainName:
    Type: String
    Default: willdiniz.com.br
  HostedZoneId:
    Type: String
    Description: O ID da Hosted Zone (criado na Fase 1)
  BucketName:
    Type: String
    Description: O nome do Bucket S3 (criado na Fase 1)

Resources:
  # 1. Certificado SSL com Validação Automática via DNS
  MyCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

  # 2. Origin Access Control (OAC) - Padrão de segurança atual
  MyOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig: 
        Description: !Sub "Acesso seguro para ${DomainName}"
        Name: !Sub "OAC-${AWS::StackName}"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # 3. Distribuição CloudFront
  MyDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Enabled: true
        DefaultRootObject: index.html
        ViewerCertificate:
          AcmCertificateArn: !Ref MyCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: S3Origin
            DomainName: !Sub "${BucketName}.s3.amazonaws.com"
            OriginAccessControlId: !GetAtt MyOAC.Id
            S3OriginConfig:
              OriginAccessIdentity: "" # OAC substitui o OAI antigo
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          ForwardedValues:
            QueryString: false

  # 4. Apontamento do DNS (Alias) para o CloudFront
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt MyDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # ID fixo da AWS para CloudFront

  # 5. Ajuste da Política do Bucket (Permite o CloudFront ler o S3)
  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "s3:GetObject"
            Effect: "Allow"
            Resource: !Sub "arn:aws:s3:::${BucketName}/*"
            Principal:
              Service: "cloudfront.amazonaws.com"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:partition:cloudfront::${AWS::AccountId}:distribution/${MyDistribution}"

Outputs:
  CloudFrontURL:
    Description: URL da CDN
    Value: !GetAtt MyDistribution.DomainName
  DistributionId:
    Description: ID da Distribuição (Anote para o Pipeline!)
    Value: !Ref MyDistribution